seo:
  site_name: 
  title: default SEO title
  description:
  keywords:
  social_image:
  author:
  favorite_image: 
social:
  instagram_username: 
  facebook_url:
  twitter_username:
design:
  background-dark_color: '#1f1005'
  background-light_color: '#E7D5B8'
  text-light_color: '#E7D5B8'
  featured_color: '#c4bc98'
 
  
